###Get all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json


###Create New Category
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "IVE"
}

###Get Category By Id
GET http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json


###Update Category By Id
PUT http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "Fashion"
}


###Delete Category By Id
DELETE http://localhost:3000/api/categories/1
X-API-Key: RAHASIA
Accept: application/json
